In [2]:
import pandas_datareader.data as pdr
import yfinance as yf
yf.pdr_override()
tw_2303 = pdr.get_data_yahoo('2303.TW')
tw_2303_1 = tw_2303.reset_index()
tw_2303_1['Date'] = tw_2303_1['Date'].map(lambda x:f'{x.year}-{x.month}-{x.day}')
tw_2303_1

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
0,2000-1-4,43.961380,44.900723,43.209900,44.524986,22.637262,332630460
1,2000-1-5,43.585640,44.524986,43.209900,44.337120,22.541752,292754299
2,2000-1-6,44.337120,44.337120,43.209900,43.397774,22.064169,248928848
3,2000-1-7,42.270554,42.646294,40.955471,42.082687,21.395555,269228882
4,2000-1-10,40.203999,43.585640,40.203999,43.209900,21.968653,380487972
...,...,...,...,...,...,...,...
5737,2023-5-18,49.950001,50.299999,49.700001,50.200001,50.200001,40947582
5738,2023-5-19,50.500000,50.500000,49.750000,50.000000,50.000000,54028480
5739,2023-5-22,49.500000,49.599998,48.700001,48.900002,48.900002,75372804
5740,2023-5-23,48.849998,49.200001,48.799999,48.900002,48.900002,39877300
5741,2023-5-24,48.799999,48.900002,48.700001,48.849998,48.849998,2704835

In [3]:
import os
from datetime import datetime
import pandas as pd
current = os.path.abspath("./")
current_date = datetime.now()
stockid = "2303.TW"
filename = f"{stockid}_{current_date.year}_{current_date.month}_{current_date.day}.csv"
file_path = os.path.join(current,'data',filename)
if not os.path.exists(file_path):
    print("建立檔案")
else:
    print("讀取檔案")

stock_dataFrame = pd.read_csv(file_path)
stock_dataFrame.info()
stock_dataFrame.index

建立檔案

FileNotFoundError: [Errno 2] No such file or directory: '/Users/roberthsu/Documents/GitHub/pythonFlask/學院_11202python應用實戰班/2023_05_11/data/2303.TW_2023_5_24.csv'

In [ ]:
import pymysql.cursors
connection = pymysql.connect(host='sql12.freesqldatabase.com',
                            user='sql12619124',
                            password='7UX5edFz35',
                            database='sql12619124',
                            charset='utf8mb4',
                            port=3306,
                            cursorclass=pymysql.cursors.DictCursor)

with connection:
    print(connection)
    print("連線成功")

<pymysql.connections.Connection object at 0x10d077c70>
連線成功

In [ ]:
def get_stockid():
    def create_connection():
        conn = None
        import pymysql.cursors
        conn = pymysql.connect(host='sql12.freesqldatabase.com',
                            user='sql12619124',
                            password='7UX5edFz35',
                            database='sql12619124',
                            charset='utf8mb4',
                            port=3306,
                            cursorclass=pymysql.cursors.DictCursor)
        return conn

    
    def select_all_tasks(conn):
        sql ="SELECT  code,name FROM codeTable"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            rows = cursor.fetchall()
            return rows
    
    
    conn = create_connection()
    rows = select_all_tasks(conn)
    conn.close()
    return rows


get_stockid()

[{'code': 1101, 'name': '台泥'},
 {'code': 1102, 'name': '亞泥'},
 {'code': 1103, 'name': '嘉泥'},
 {'code': 1104, 'name': '環泥'},
 {'code': 1108, 'name': '幸福'},
 {'code': 1109, 'name': '信大'},
 {'code': 1110, 'name': '東泥'},
 {'code': 1201, 'name': '味全'},
 {'code': 1203, 'name': '味王'},
 {'code': 1210, 'name': '大成'},
 {'code': 1213, 'name': '大飲'},
 {'code': 1215, 'name': '卜蜂'},
 {'code': 1216, 'name': '統一'},
 {'code': 1217, 'name': '愛之味'},
 {'code': 1218, 'name': '泰山'},
 {'code': 1219, 'name': '福壽'},
 {'code': 1220, 'name': '台榮'},
 {'code': 1225, 'name': '福懋油'},
 {'code': 1227, 'name': '佳格'},
 {'code': 1229, 'name': '聯華'},
 {'code': 1231, 'name': '聯華食'},
 {'code': 1232, 'name': '大統益'},
 {'code': 1233, 'name': '天仁'},
 {'code': 1234, 'name': '黑松'},
 {'code': 1235, 'name': '興泰'},
 {'code': 1236, 'name': '宏亞'},
 {'code': 1256, 'name': '鮮活果汁-KY'},
 {'code': 1301, 'name': '台塑'},
 {'code': 1303, 'name': '南亞'},
 {'code': 1304, 'name': '台聚'},
 {'code': 1305, 'name': '華夏'},
 {'code': 1307, 'name': '三芳'},
 {'code': 1308, 'name': '亞聚'},
 {'code': 1309, 'name': '台達化'},
 {'code': 1310, 'name': '台苯'},
 {'code': 1312, 'name': '國喬'},
 {'code': 1313, 'name': '聯成'},
 {'code': 1314, 'name': '中石化'},
 {'code': 1315, 'name': '達新'},
 {'code': 1316, 'name': '上曜'},
 {'code': 1319, 'name': '東陽'},
 {'code': 1321, 'name': '大洋'},
 {'code': 1323, 'name': '永裕'},
 {'code': 1324, 'name': '地球'},
 {'code': 1325, 'name': '恆大'},
 {'code': 1326, 'name': '台化'},
 {'code': 1337, 'name': '再生-KY'},
 {'code': 1338, 'name': '廣華-KY'},
 {'code': 1339, 'name': '昭輝'},
 {'code': 1340, 'name': '勝悅-KY'},
 {'code': 1341, 'name': '富林-KY'},
 {'code': 1342, 'name': '八貫'},
 {'code': 1402, 'name': '遠東新'},
 {'code': 1409, 'name': '新纖'},
 {'code': 1410, 'name': '南染'},
 {'code': 1413, 'name': '宏洲'},
 {'code': 1414, 'name': '東和'},
 {'code': 1416, 'name': '廣豐'},
 {'code': 1417, 'name': '嘉裕'},
 {'code': 1418, 'name': '東華'},
 {'code': 1419, 'name': '新紡'},
 {'code': 1423, 'name': '利華'},
 {'code': 1432, 'name': '大魯閣'},
 {'code': 1434, 'name': '福懋'},
 {'code': 1435, 'name': '中福'},
 {'code': 1436, 'name': '華友聯'},
 {'code': 1437, 'name': '勤益控'},
 {'code': 1438, 'name': '三地開發'},
 {'code': 1439, 'name': '雋揚'},
 {'code': 1440, 'name': '南紡'},
 {'code': 1441, 'name': '大東'},
 {'code': 1442, 'name': '名軒'},
 {'code': 1443, 'name': '立益物流'},
 {'code': 1444, 'name': '力麗'},
 {'code': 1445, 'name': '大宇'},
 {'code': 1446, 'name': '宏和'},
 {'code': 1447, 'name': '力鵬'},
 {'code': 1449, 'name': '佳和'},
 {'code': 1451, 'name': '年興'},
 {'code': 1452, 'name': '宏益'},
 {'code': 1453, 'name': '大將'},
 {'code': 1454, 'name': '台富'},
 {'code': 1455, 'name': '集盛'},
 {'code': 1456, 'name': '怡華'},
 {'code': 1457, 'name': '宜進'},
 {'code': 1459, 'name': '聯發'},
 {'code': 1460, 'name': '宏遠'},
 {'code': 1463, 'name': '強盛'},
 {'code': 1464, 'name': '得力'},
 {'code': 1465, 'name': '偉全'},
 {'code': 1466, 'name': '聚隆'},
 {'code': 1467, 'name': '南緯'},
 {'code': 1468, 'name': '昶和'},
 {'code': 1470, 'name': '大統新創'},
 {'code': 1471, 'name': '首利'},
 {'code': 1472, 'name': '三洋實業'},
 {'code': 1473, 'name': '台南'},
 {'code': 1474, 'name': '弘裕'},
 {'code': 1475, 'name': '業旺'},
 {'code': 1476, 'name': '儒鴻'},
 {'code': 1477, 'name': '聚陽'},
 {'code': 1503, 'name': '士電'},
 {'code': 1504, 'name': '東元'},
 {'code': 1506, 'name': '正道'},
 {'code': 1512, 'name': '瑞利'},
 {'code': 1513, 'name': '中興電'},
 {'code': 1514, 'name': '亞力'},
 {'code': 1515, 'name': '力山'},
 {'code': 1516, 'name': '川飛'},
 {'code': 1517, 'name': '利奇'},
 {'code': 1519, 'name': '華城'},
 {'code': 1521, 'name': '大億'},
 {'code': 1522, 'name': '堤維西'},
 {'code': 1524, 'name': '耿鼎'},
 {'code': 1525, 'name': '江申'},
 {'code': 1526, 'name': '日馳'},
 {'code': 1527, 'name': '鑽全'},
 {'code': 1528, 'name': '恩德'},
 {'code': 1529, 'name': '樂事綠能'},
 {'code': 1530, 'name': '亞崴'},
 {'code': 1531, 'name': '高林股'},
 {'code': 1532, 'name': '勤美'},
 {'code': 1533, 'name': '車王電'},
 {'code': 1535, 'name': '中宇'},
 {'code': 1536, 'name': '和大'},
 {'code': 1537, 'name': '廣隆'},
 {'code': 1538, 'name': '正峰'},
 {'code': 1539, 'name': '巨庭'},
 {'code': 1540, 'name': '喬福'},
 {'code': 1541, 'name': '錩泰'},
 {'code': 1558, 'name': '伸興'},
 {'code': 1560, 'name': '中砂'},
 {'code': 1568, 'name': '倉佑'},
 {'code': 1582, 'name': '信錦'},
 {'code': 1583, 'name': '程泰'},
 {'code': 1587, 'name': '吉茂'},
 {'code': 1589, 'name': '永冠-KY'},
 {'code': 1590, 'name': '亞德客-KY'},
 {'code': 1597, 'name': '直得'},
 {'code': 1598, 'name': '岱宇'},
 {'code': 1603, 'name': '華電'},
 {'code': 1604, 'name': '聲寶'},
 {'code': 1605, 'name': '華新'},
 {'code': 1608, 'name': '華榮'},
 {'code': 1609, 'name': '大亞'},
 {'code': 1611, 'name': '中電'},
 {'code': 1612, 'name': '宏泰'},
 {'code': 1614, 'name': '三洋電'},
 {'code': 1615, 'name': '大山'},
 {'code': 1616, 'name': '億泰'},
 {'code': 1617, 'name': '榮星'},
 {'code': 1618, 'name': '合機'},
 {'code': 1626, 'name': '艾美特-KY'},
 {'code': 1701, 'name': '中化'},
 {'code': 1702, 'name': '南僑'},
 {'code': 1707, 'name': '葡萄王'},
 {'code': 1708, 'name': '東鹼'},
 {'code': 1709, 'name': '和益'},
 {'code': 1710, 'name': '東聯'},
 {'code': 1711, 'name': '永光'},
 {'code': 1712, 'name': '興農'},
 {'code': 1713, 'name': '國化'},
 {'code': 1714, 'name': '和桐'},
 {'code': 1717, 'name': '長興'},
 {'code': 1718, 'name': '中纖'},
 {'code': 1720, 'name': '生達'},
 {'code': 1721, 'name': '三晃'},
 {'code': 1722, 'name': '台肥'},
 {'code': 1723, 'name': '中碳'},
 {'code': 1725, 'name': '元禎'},
 {'code': 1726, 'name': '永記'},
 {'code': 1727, 'name': '中華化'},
 {'code': 1730, 'name': '花仙子'},
 {'code': 1731, 'name': '美吾華'},
 {'code': 1732, 'name': '毛寶'},
 {'code': 1733, 'name': '五鼎'},
 {'code': 1734, 'name': '杏輝'},
 {'code': 1735, 'name': '日勝化'},
 {'code': 1736, 'name': '喬山'},
 {'code': 1737, 'name': '臺鹽'},
 {'code': 1752, 'name': '南光'},
 {'code': 1760, 'name': '寶齡富錦'},
 {'code': 1762, 'name': '中化生'},
 {'code': 1773, 'name': '勝一'},
 {'code': 1776, 'name': '展宇'},
 {'code': 1783, 'name': '和康生'},
 {'code': 1786, 'name': '科妍'},
 {'code': 1789, 'name': '神隆'},
 {'code': 1795, 'name': '美時'},
 {'code': 1802, 'name': '台玻'},
 {'code': 1805, 'name': '寶徠'},
 {'code': 1806, 'name': '冠軍'},
 {'code': 1808, 'name': '潤隆'},
 {'code': 1809, 'name': '中釉'},
 {'code': 1810, 'name': '和成'},
 {'code': 1817, 'name': '凱撒衛'},
 {'code': 1903, 'name': '士紙'},
 {'code': 1904, 'name': '正隆'},
 {'code': 1905, 'name': '華紙'},
 {'code': 1906, 'name': '寶隆'},
 {'code': 1907, 'name': '永豐餘'},
 {'code': 1909, 'name': '榮成'},
 {'code': 2002, 'name': '中鋼'},
 {'code': 2006, 'name': '東和鋼鐵'},
 {'code': 2007, 'name': '燁興'},
 {'code': 2008, 'name': '高興昌'},
 {'code': 2009, 'name': '第一銅'},
 {'code': 2010, 'name': '春源'},
 {'code': 2012, 'name': '春雨'},
 {'code': 2013, 'name': '中鋼構'},
 {'code': 2014, 'name': '中鴻'},
 {'code': 2015, 'name': '豐興'},
 {'code': 2017, 'name': '官田鋼'},
 {'code': 2020, 'name': '美亞'},
 {'code': 2022, 'name': '聚亨'},
 {'code': 2023, 'name': '燁輝'},
 {'code': 2024, 'name': '志聯'},
 {'code': 2025, 'name': '千興'},
 {'code': 2027, 'name': '大成鋼'},
 {'code': 2028, 'name': '威致'},
 {'code': 2029, 'name': '盛餘'},
 {'code': 2030, 'name': '彰源'},
 {'code': 2031, 'name': '新光鋼'},
 {'code': 2032, 'name': '新鋼'},
 {'code': 2033, 'name': '佳大'},
 {'code': 2034, 'name': '允強'},
 {'code': 2038, 'name': '海光'},
 {'code': 2049, 'name': '上銀'},
 {'code': 2059, 'name': '川湖'},
 {'code': 2062, 'name': '橋椿'},
 {'code': 2069, 'name': '運錩'},
 {'code': 2101, 'name': '南港'},
 {'code': 2102, 'name': '泰豐'},
 {'code': 2103, 'name': '台橡'},
 {'code': 2104, 'name': '國際中橡'},
 {'code': 2105, 'name': '正新'},
 {'code': 2106, 'name': '建大'},
 {'code': 2107, 'name': '厚生'},
 {'code': 2108, 'name': '南帝'},
 {'code': 2109, 'name': '華豐'},
 {'code': 2114, 'name': '鑫永銓'},
 {'code': 2115, 'name': '六暉-KY'},
 {'code': 2201, 'name': '裕隆'},
 {'code': 2204, 'name': '中華'},
 {'code': 2206, 'name': '三陽工業'},
 {'code': 2207, 'name': '和泰車'},
 {'code': 2208, 'name': '台船'},
 {'code': 2211, 'name': '長榮鋼'},
 {'code': 2227, 'name': '裕日車'},
 {'code': 2228, 'name': '劍麟'},
 {'code': 2231, 'name': '為升'},
 {'code': 2233, 'name': '宇隆'},
 {'code': 2236, 'name': '百達-KY'},
 {'code': 2239, 'name': '英利-KY'},
 {'code': 2241, 'name': '艾姆勒'},
 {'code': 2243, 'name': '宏旭-KY'},
 {'code': 2247, 'name': '汎德永業'},
 {'code': 2250, 'name': 'IKKA-KY'},
 {'code': 2301, 'name': '光寶科'},
 {'code': 2302, 'name': '麗正'},
 {'code': 2303, 'name': '聯電'},
 {'code': 2305, 'name': '全友'},
 {'code': 2308, 'name': '台達電'},
 {'code': 2312, 'name': '金寶'},
 {'code': 2313, 'name': '華通'},
 {'code': 2314, 'name': '台揚'},
 {'code': 2316, 'name': '楠梓電'},
 {'code': 2317, 'name': '鴻海'},
 {'code': 2321, 'name': '東訊'},
 {'code': 2323, 'name': '中環'},
 {'code': 2324, 'name': '仁寶'},
 {'code': 2327, 'name': '國巨'},
 {'code': 2328, 'name': '廣宇'},
 {'code': 2329, 'name': '華泰'},
 {'code': 2330, 'name': '台積電'},
 {'code': 2331, 'name': '精英'},
 {'code': 2332, 'name': '友訊'},
 {'code': 2337, 'name': '旺宏'},
 {'code': 2338, 'name': '光罩'},
 {'code': 2340, 'name': '台亞'},
 {'code': 2342, 'name': '茂矽'},
 {'code': 2344, 'name': '華邦電'},
 {'code': 2345, 'name': '智邦'},
 {'code': 2347, 'name': '聯強'},
 {'code': 2348, 'name': '海悅'},
 {'code': 2349, 'name': '錸德'},
 {'code': 2351, 'name': '順德'},
 {'code': 2352, 'name': '佳世達'},
 {'code': 2353, 'name': '宏碁'},
 {'code': 2354, 'name': '鴻準'},
 {'code': 2355, 'name': '敬鵬'},
 {'code': 2356, 'name': '英業達'},
 {'code': 2357, 'name': '華碩'},
 {'code': 2358, 'name': '廷鑫'},
 {'code': 2359, 'name': '所羅門'},
 {'code': 2360, 'name': '致茂'},
 {'code': 2362, 'name': '藍天'},
 {'code': 2363, 'name': '矽統'},
 {'code': 2364, 'name': '倫飛'},
 {'code': 2365, 'name': '昆盈'},
 {'code': 2367, 'name': '燿華'},
 {'code': 2368, 'name': '金像電'},
 {'code': 2369, 'name': '菱生'},
 {'code': 2371, 'name': '大同'},
 {'code': 2373, 'name': '震旦行'},
 {'code': 2374, 'name': '佳能'},
 {'code': 2375, 'name': '凱美'},
 {'code': 2376, 'name': '技嘉'},
 {'code': 2377, 'name': '微星'},
 {'code': 2379, 'name': '瑞昱'},
 {'code': 2380, 'name': '虹光'},
 {'code': 2382, 'name': '廣達'},
 {'code': 2383, 'name': '台光電'},
 {'code': 2385, 'name': '群光'},
 {'code': 2387, 'name': '精元'},
 {'code': 2388, 'name': '威盛'},
 {'code': 2390, 'name': '云辰'},
 {'code': 2392, 'name': '正崴'},
 {'code': 2393, 'name': '億光'},
 {'code': 2395, 'name': '研華'},
 {'code': 2397, 'name': '友通'},
 {'code': 2399, 'name': '映泰'},
 {'code': 2401, 'name': '凌陽'},
 {'code': 2402, 'name': '毅嘉'},
 {'code': 2404, 'name': '漢唐'},
 {'code': 2405, 'name': '輔信'},
 {'code': 2406, 'name': '國碩'},
 {'code': 2408, 'name': '南亞科'},
 {'code': 2409, 'name': '友達'},
 {'code': 2412, 'name': '中華電'},
 {'code': 2413, 'name': '環科'},
 {'code': 2414, 'name': '精技'},
 {'code': 2415, 'name': '錩新'},
 {'code': 2417, 'name': '圓剛'},
 {'code': 2419, 'name': '仲琦'},
 {'code': 2420, 'name': '新巨'},
 {'code': 2421, 'name': '建準'},
 {'code': 2423, 'name': '固緯'},
 {'code': 2424, 'name': '隴華'},
 {'code': 2425, 'name': '承啟'},
 {'code': 2426, 'name': '鼎元'},
 {'code': 2427, 'name': '三商電'},
 {'code': 2428, 'name': '興勤'},
 {'code': 2429, 'name': '銘旺科'},
 {'code': 2430, 'name': '燦坤'},
 {'code': 2431, 'name': '聯昌'},
 {'code': 2433, 'name': '互盛電'},
 {'code': 2434, 'name': '統懋'},
 {'code': 2436, 'name': '偉詮電'},
 {'code': 2438, 'name': '翔耀'},
 {'code': 2439, 'name': '美律'},
 {'code': 2440, 'name': '太空梭'},
 {'code': 2441, 'name': '超豐'},
 {'code': 2442, 'name': '新美齊'},
 {'code': 2443, 'name': '昶虹'},
 {'code': 2444, 'name': '兆勁'},
 {'code': 2449, 'name': '京元電子'},
 {'code': 2450, 'name': '神腦'},
 {'code': 2451, 'name': '創見'},
 {'code': 2453, 'name': '凌群'},
 {'code': 2454, 'name': '聯發科'},
 {'code': 2455, 'name': '全新'},
 {'code': 2457, 'name': '飛宏'},
 {'code': 2458, 'name': '義隆'},
 {'code': 2459, 'name': '敦吉'},
 {'code': 2460, 'name': '建通'},
 {'code': 2461, 'name': '光群雷'},
 {'code': 2462, 'name': '良得電'},
 {'code': 2464, 'name': '盟立'},
 {'code': 2465, 'name': '麗臺'},
 {'code': 2466, 'name': '冠西電'},
 {'code': 2467, 'name': '志聖'},
 {'code': 2468, 'name': '華經'},
 {'code': 2471, 'name': '資通'},
 {'code': 2472, 'name': '立隆電'},
 {'code': 2474, 'name': '可成'},
 {'code': 2476, 'name': '鉅祥'},
 {'code': 2477, 'name': '美隆電'},
 {'code': 2478, 'name': '大毅'},
 {'code': 2480, 'name': '敦陽科'},
 {'code': 2481, 'name': '強茂'},
 {'code': 2482, 'name': '連宇'},
 {'code': 2483, 'name': '百容'},
 {'code': 2484, 'name': '希華'},
 {'code': 2485, 'name': '兆赫'},
 {'code': 2486, 'name': '一詮'},
 {'code': 2488, 'name': '漢平'},
 {'code': 2489, 'name': '瑞軒'},
 {'code': 2491, 'name': '吉祥全'},
 {'code': 2492, 'name': '華新科'},
 {'code': 2493, 'name': '揚博'},
 {'code': 2495, 'name': '普安'},
 {'code': 2496, 'name': '卓越'},
 {'code': 2497, 'name': '怡利電'},
 {'code': 2498, 'name': '宏達電'},
 {'code': 2501, 'name': '國建'},
 {'code': 2504, 'name': '國產'},
 {'code': 2505, 'name': '國揚'},
 {'code': 2506, 'name': '太設'},
 {'code': 2509, 'name': '全坤建'},
 {'code': 2511, 'name': '太子'},
 {'code': 2514, 'name': '龍邦'},
 {'code': 2515, 'name': '中工'},
 {'code': 2516, 'name': '新建'},
 {'code': 2520, 'name': '冠德'},
 {'code': 2524, 'name': '京城'},
 {'code': 2527, 'name': '宏璟'},
 {'code': 2528, 'name': '皇普'},
 {'code': 2530, 'name': '華建'},
 {'code': 2534, 'name': '宏盛'},
 {'code': 2535, 'name': '達欣工'},
 {'code': 2536, 'name': '宏普'},
 {'code': 2537, 'name': '聯上發'},
 {'code': 2538, 'name': '基泰'},
 {'code': 2539, 'name': '櫻花建'},
 {'code': 2540, 'name': '愛山林'},
 {'code': 2542, 'name': '興富發'},
 {'code': 2543, 'name': '皇昌'},
 {'code': 2545, 'name': '皇翔'},
 {'code': 2546, 'name': '根基'},
 {'code': 2547, 'name': '日勝生'},
 {'code': 2548, 'name': '華固'},
 {'code': 2597, 'name': '潤弘'},
 {'code': 2601, 'name': '益航'},
 {'code': 2603, 'name': '長榮'},
 {'code': 2605, 'name': '新興'},
 {'code': 2606, 'name': '裕民'},
 {'code': 2607, 'name': '榮運'},
 {'code': 2608, 'name': '嘉里大榮'},
 {'code': 2609, 'name': '陽明'},
 {'code': 2610, 'name': '華航'},
 {'code': 2611, 'name': '志信'},
 {'code': 2612, 'name': '中航'},
 {'code': 2613, 'name': '中櫃'},
 {'code': 2614, 'name': '東森'},
 {'code': 2615, 'name': '萬海'},
 {'code': 2616, 'name': '山隆'},
 {'code': 2617, 'name': '台航'},
 {'code': 2618, 'name': '長榮航'},
 {'code': 2630, 'name': '亞航'},
 {'code': 2633, 'name': '台灣高鐵'},
 {'code': 2634, 'name': '漢翔'},
 {'code': 2636, 'name': '台驊投控'},
 {'code': 2637, 'name': '慧洋-KY'},
 {'code': 2642, 'name': '宅配通'},
 {'code': 2645, 'name': '長榮航太'},
 {'code': 2701, 'name': '萬企'},
 {'code': 2702, 'name': '華園'},
 {'code': 2704, 'name': '國賓'},
 {'code': 2705, 'name': '六福'},
 {'code': 2706, 'name': '第一店'},
 {'code': 2707, 'name': '晶華'},
 {'code': 2712, 'name': '遠雄來'},
 {'code': 2722, 'name': '夏都'},
 {'code': 2723, 'name': '美食-KY'},
 {'code': 2727, 'name': '王品'},
 {'code': 2731, 'name': '雄獅'},
 {'code': 2739, 'name': '寒舍'},
 {'code': 2748, 'name': '雲品'},
 {'code': 2753, 'name': '八方雲集'},
 {'code': 2801, 'name': '彰銀'},
 {'code': 2809, 'name': '京城銀'},
 {'code': 2812, 'name': '台中銀'},
 {'code': 2816, 'name': '旺旺保'},
 {'code': 2820, 'name': '華票'},
 {'code': 2832, 'name': '台產'},
 {'code': 2834, 'name': '臺企銀'},
 {'code': 2836, 'name': '高雄銀'},
 {'code': 2838, 'name': '聯邦銀'},
 {'code': 2845, 'name': '遠東銀'},
 {'code': 2849, 'name': '安泰銀'},
 {'code': 2850, 'name': '新產'},
 {'code': 2851, 'name': '中再保'},
 {'code': 2852, 'name': '第一保'},
 {'code': 2855, 'name': '統一證'},
 {'code': 2867, 'name': '三商壽'},
 {'code': 2880, 'name': '華南金'},
 {'code': 2881, 'name': '富邦金'},
 {'code': 2882, 'name': '國泰金'},
 {'code': 2883, 'name': '開發金'},
 {'code': 2884, 'name': '玉山金'},
 {'code': 2885, 'name': '元大金'},
 {'code': 2886, 'name': '兆豐金'},
 {'code': 2887, 'name': '台新金'},
 {'code': 2888, 'name': '新光金'},
 {'code': 2889, 'name': '國票金'},
 {'code': 2890, 'name': '永豐金'},
 {'code': 2891, 'name': '中信金'},
 {'code': 2892, 'name': '第一金'},
 {'code': 2897, 'name': '王道銀行'},
 {'code': 2901, 'name': '欣欣'},
 {'code': 2903, 'name': '遠百'},
 {'code': 2904, 'name': '匯僑'},
 {'code': 2905, 'name': '三商'},
 {'code': 2906, 'name': '高林'},
 {'code': 2908, 'name': '特力'},
 {'code': 2910, 'name': '統領'},
 {'code': 2911, 'name': '麗嬰房'},
 {'code': 2912, 'name': '統一超'},
 {'code': 2913, 'name': '農林'},
 {'code': 2915, 'name': '潤泰全'},
 {'code': 2923, 'name': '鼎固-KY'},
 {'code': 2929, 'name': '淘帝-KY'},
 {'code': 2939, 'name': '凱羿-KY'},
 {'code': 2945, 'name': '三商家購'},
 {'code': 3002, 'name': '歐格'},
 {'code': 3003, 'name': '健和興'},
 {'code': 3004, 'name': '豐達科'},
 {'code': 3005, 'name': '神基'},
 {'code': 3006, 'name': '晶豪科'},
 {'code': 3008, 'name': '大立光'},
 {'code': 3010, 'name': '華立'},
 {'code': 3011, 'name': '今皓'},
 {'code': 3013, 'name': '晟銘電'},
 {'code': 3014, 'name': '聯陽'},
 {'code': 3015, 'name': '全漢'},
 {'code': 3016, 'name': '嘉晶'},
 {'code': 3017, 'name': '奇鋐'},
 {'code': 3018, 'name': '隆銘綠能'},
 {'code': 3019, 'name': '亞光'},
 {'code': 3021, 'name': '鴻名'},
 {'code': 3022, 'name': '威強電'},
 {'code': 3023, 'name': '信邦'},
 {'code': 3024, 'name': '憶聲'},
 {'code': 3025, 'name': '星通'},
 {'code': 3026, 'name': '禾伸堂'},
 {'code': 3027, 'name': '盛達'},
 {'code': 3028, 'name': '增你強'},
 {'code': 3029, 'name': '零壹'},
 {'code': 3030, 'name': '德律'},
 {'code': 3031, 'name': '佰鴻'},
 {'code': 3032, 'name': '偉訓'},
 {'code': 3033, 'name': '威健'},
 {'code': 3034, 'name': '聯詠'},
 {'code': 3035, 'name': '智原'},
 {'code': 3036, 'name': '文曄'},
 {'code': 3037, 'name': '欣興'},
 {'code': 3038, 'name': '全台'},
 {'code': 3040, 'name': '遠見'},
 {'code': 3041, 'name': '揚智'},
 {'code': 3042, 'name': '晶技'},
 {'code': 3043, 'name': '科風'},
 {'code': 3044, 'name': '健鼎'},
 {'code': 3045, 'name': '台灣大'},
 {'code': 3046, 'name': '建碁'},
 {'code': 3047, 'name': '訊舟'},
 {'code': 3048, 'name': '益登'},
 {'code': 3049, 'name': '和鑫'},
 {'code': 3050, 'name': '鈺德'},
 {'code': 3051, 'name': '力特'},
 {'code': 3052, 'name': '夆典'},
 {'code': 3054, 'name': '立萬利'},
 {'code': 3055, 'name': '蔚華科'},
 {'code': 3056, 'name': '總太'},
 {'code': 3057, 'name': '喬鼎'},
 {'code': 3058, 'name': '立德'},
 {'code': 3059, 'name': '華晶科'},
 {'code': 3060, 'name': '銘異'},
 {'code': 3062, 'name': '建漢'},
 {'code': 3090, 'name': '日電貿'},
 {'code': 3092, 'name': '鴻碩'},
 {'code': 3094, 'name': '聯傑'},
 {'code': 3130, 'name': '一零四'},
 {'code': 3138, 'name': '耀登'},
 {'code': 3149, 'name': '正達'},
 {'code': 3164, 'name': '景岳'},
 {'code': 3167, 'name': '大量'},
 {'code': 3189, 'name': '景碩'},
 {'code': 3209, 'name': '全科'},
 {'code': 3229, 'name': '晟鈦'},
 {'code': 3231, 'name': '緯創'},
 {'code': 3257, 'name': '虹冠電'},
 {'code': 3266, 'name': '昇陽'},
 {'code': 3296, 'name': '勝德'},
 {'code': 3305, 'name': '昇貿'},
 {'code': 3308, 'name': '聯德'},
 {'code': 3311, 'name': '閎暉'},
 {'code': 3312, 'name': '弘憶股'},
 {'code': 3321, 'name': '同泰'},
 {'code': 3338, 'name': '泰碩'},
 {'code': 3346, 'name': '麗清'},
 {'code': 3356, 'name': '奇偶'},
 {'code': 3376, 'name': '新日興'},
 {'code': 3380, 'name': '明泰'},
 {'code': 3406, 'name': '玉晶光'},
 {'code': 3413, 'name': '京鼎'},
 {'code': 3416, 'name': '融程電'},
 {'code': 3419, 'name': '譁裕'},
 {'code': 3432, 'name': '台端'},
 {'code': 3437, 'name': '榮創'},
 {'code': 3443, 'name': '創意'},
 {'code': 3447, 'name': '展達'},
 {'code': 3450, 'name': '聯鈞'},
 {'code': 3454, 'name': '晶睿'},
 {'code': 3481, 'name': '群創'},
 {'code': 3494, 'name': '誠研'},
 {'code': 3501, 'name': '維熹'},
 {'code': 3504, 'name': '揚明光'},
 {'code': 3515, 'name': '華擎'},
 {'code': 3518, 'name': '柏騰'},
 {'code': 3528, 'name': '安馳'},
 {'code': 3530, 'name': '晶相光'},
 {'code': 3532, 'name': '台勝科'},
 {'code': 3533, 'name': '嘉澤'},
 {'code': 3535, 'name': '晶彩科'},
 {'code': 3536, 'name': '誠創'},
 {'code': 3543, 'name': '州巧'},
 {'code': 3545, 'name': '敦泰'},
 {'code': 3550, 'name': '聯穎'},
 {'code': 3557, 'name': '嘉威'},
 {'code': 3563, 'name': '牧德'},
 {'code': 3576, 'name': '聯合再生'},
 {'code': 3583, 'name': '辛耘'},
 {'code': 3588, 'name': '通嘉'},
 {'code': 3591, 'name': '艾笛森'},
 {'code': 3592, 'name': '瑞鼎'},
 {'code': 3593, 'name': '力銘'},
 {'code': 3596, 'name': '智易'},
 {'code': 3605, 'name': '宏致'},
 {'code': 3607, 'name': '谷崧'},
 {'code': 3617, 'name': '碩天'},
 {'code': 3622, 'name': '洋華'},
 {'code': 3645, 'name': '達邁'},
 {'code': 3652, 'name': '精聯'},
 {'code': 3653, 'name': '健策'},
 {'code': 3661, 'name': '世芯-KY'},
 {'code': 3665, 'name': '貿聯-KY'},
 {'code': 3669, 'name': '圓展'},
 {'code': 3673, 'name': 'TPK-KY'},
 {'code': 3679, 'name': '新至陞'},
 {'code': 3682, 'name': '亞太電'},
 {'code': 3686, 'name': '達能'},
 {'code': 3694, 'name': '海華'},
 {'code': 3701, 'name': '大眾控'},
 {'code': 3702, 'name': '大聯大'},
 {'code': 3703, 'name': '欣陸'},
 {'code': 3704, 'name': '合勤控'},

In [5]:
#搜尋出股票特定的年份

import os
from datetime import datetime
import pandas as pd
current = os.path.abspath("./")
current_date = datetime.now()
stockid = "2303.TW"
filename = f"{stockid}_{current_date.year}_{current_date.month}_{current_date.day}.csv"
file_path = os.path.join(current,'data',filename)
if not os.path.exists(file_path):
    print("建立檔案")
else:
    print("讀取檔案")

stock_dataFrame = pd.read_csv(file_path)
stock_dataFrame

讀取檔案

,Date,Open,High,Low,Close,Adj Close,Volume
0,2000-01-04,43.961380,44.900723,43.209900,44.524986,22.637262,332630460
1,2000-01-05,43.585640,44.524986,43.209900,44.337120,22.541750,292754299
2,2000-01-06,44.337120,44.337120,43.209900,43.397774,22.064167,248928848
3,2000-01-07,42.270554,42.646294,40.955471,42.082687,21.395554,269228882
4,2000-01-10,40.203999,43.585640,40.203999,43.209900,21.968653,380487972
...,...,...,...,...,...,...,...
5737,2023-05-18,49.950001,50.299999,49.700001,50.200001,50.200001,40947582
5738,2023-05-19,50.500000,50.500000,49.750000,50.000000,50.000000,54028480
5739,2023-05-22,49.500000,49.599998,48.700001,48.900002,48.900002,75372804
5740,2023-05-23,48.849998,49.200001,48.799999,48.900002,48.900002,39877300
5741,2023-05-24,48.799999,49.000000,48.700001,49.000000,49.000000,3151860